#!/bin/sh
RandomMsg() {
	RNUM=$((1 + $RANDOM % 5))
	case $RNUM in
		1) echo "General stability improvements for optimised user experience";;
		2) echo "Improved system software performance and stability for improved user experience";;
		3) echo "General system stability improvements to enhance the user's experience.";;
		4) echo "General security fixes for improved user experience";;
		5) echo "Fixed SystemD from becoming sentient, enslaving all computers into an evil botnet bent on the destruction of humanity (hopefully this won't happen again, fingers crossed 🤞🏻)";;
	esac
}
git add . && \
git commit -m "$(RandomMsg)" && \
git push -u origin main
